version: '3.5'

services:
  pycontw-2026-frontend:
    container_name: pycontw-2026-frontend
    restart: always
    build:
      context: .
    networks:
      - network

networks:
  network:
    external: true
    name: network-2026
