name: Test, build, deploy

on:
  push:
    branches:
      - main

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [24]
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - run: pnpm install --frozen-lockfile

      - name: Run linter 👀
        run: pnpm run lint

      - name: Build 👷🏽
        run: pnpm run generate
        env:
          NUXT_API_URL: https://staging.pycon.tw/prs
          NUXT_API_AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
          GOOGLE_TAG_MANAGER_ID: ${{ secrets.GOOGLE_TAG_MANAGER_ID }}

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
          CLEAN: true
